
project:
  type: website
  output-dir: _docs
  preview:
    port: 3000
    browser: false

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 4

website:
  title: "pyndamics3"
  site-url: "https://bblais.github.io/pyndamics3/"
  description: "Python Numerical Dynamics Simulator"
  twitter-card: true
  open-graph: true
  reader-mode: true
  repo-branch: master
  repo-url: "https://github.com/bblais/pyndamics3/tree/master/"
  repo-actions: [issue]
  navbar:
    background: primary
    search: true
    right:
      - icon: github
        href: "https://github.com/bblais/pyndamics3/tree/master/"
  sidebar:
    style: "floating"

metadata-files: 
  - sidebar.yml
  - custom.yml
